#### Softmax Function

In [1]:
import numpy as np
import pandas as pd

z = [1,2,3,4,1,2,3]
arr = np.array(z, dtype = float)
softmax = np.exp(arr)/np.sum(np.exp(arr))
softmax, np.sum(softmax)

(array([0.02364054, 0.06426166, 0.1746813 , 0.474833  , 0.02364054,
        0.06426166, 0.1746813 ]), 0.9999999999999999)

Softmax Regression is also known as Multi-class Logistic Regression.

In [2]:
x = np.array([[.1,.5],[1.1,2.3],[-1.1, -2.3],[-1.5, -2.5]])
y = [0,1,2,2]

In [3]:
from sklearn.preprocessing import label_binarize

y = label_binarize(y,classes = [0,1,2])
y

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]], dtype=int32)

In [4]:
w = np.array([[.1,.2,.3], [.1,.2,.3]])

bias = np.array([.01,.1,.1])

w, bias

(array([[0.1, 0.2, 0.3],
        [0.1, 0.2, 0.3]]), array([0.01, 0.1 , 0.1 ]))

In [5]:
x

array([[ 0.1,  0.5],
       [ 1.1,  2.3],
       [-1.1, -2.3],
       [-1.5, -2.5]])

In [6]:
x_new = np.c_[[1,1,1,1],x] #x with ones
x_new

array([[ 1. ,  0.1,  0.5],
       [ 1. ,  1.1,  2.3],
       [ 1. , -1.1, -2.3],
       [ 1. , -1.5, -2.5]])

In [7]:
w_b = np.r_[[bias],w]
w_b

array([[0.01, 0.1 , 0.1 ],
       [0.1 , 0.2 , 0.3 ],
       [0.1 , 0.2 , 0.3 ]])

In [8]:
z = np.dot(x_new,w_b)
z

array([[ 0.07,  0.22,  0.28],
       [ 0.35,  0.78,  1.12],
       [-0.33, -0.58, -0.92],
       [-0.39, -0.7 , -1.1 ]])

In [9]:
a = np.exp(z)
a

array([[1.07250818, 1.24607673, 1.32312981],
       [1.41906755, 2.18147227, 3.0648542 ],
       [0.71892373, 0.55989837, 0.39851904],
       [0.67705687, 0.4965853 , 0.33287108]])

In [12]:
b = np.sum(softmax)
b

0.9999999999999999

In [13]:
softmax = a/b
softmax

array([[1.07250818, 1.24607673, 1.32312981],
       [1.41906755, 2.18147227, 3.0648542 ],
       [0.71892373, 0.55989837, 0.39851904],
       [0.67705687, 0.4965853 , 0.33287108]])

In [14]:
np.argmax(softmax,1) #predicted output

array([2, 2, 0, 0], dtype=int32)

This is the initial prediction which is way off as compared to original target `y = [0,1,2,2]`

In [15]:
bb = -np.sum(y*np.log(softmax),1) #cross entropy
bb

array([-0.07, -0.78,  0.92,  1.1 ])